-- Create the table according to the EDA
CREATE TABLE Bronze.FreshdeskTickets (
    cc_emails                 NVARCHAR(MAX),
    fwd_emails                NVARCHAR(MAX),
    reply_cc_emails           NVARCHAR(MAX),
    ticket_cc_emails          NVARCHAR(MAX),
    ticket_bcc_emails         NVARCHAR(MAX),
    fr_escalated              BIT,
    spam                      BIT,
    email_config_id           BIGINT,
    group_id                  BIGINT,
    priority                  INT,
    requester_id              BIGINT,
    responder_id              BIGINT,
    source                    INT,
    company_id                BIGINT,
    status                    INT,
    subject                   NVARCHAR(MAX),
    association_type          INT,
    support_email             NVARCHAR(500),
    to_emails                 NVARCHAR(MAX),
    product_id                BIGINT,
    id                        BIGINT,
    type                      NVARCHAR(200),
    due_by                    DATETIME2,
    fr_due_by                 DATETIME2,
    is_escalated              BIT,
    custom_fields             NVARCHAR(MAX),
    created_at                DATETIME2,
    updated_at                DATETIME2,
    associated_tickets_count  INT,
    tags                      NVARCHAR(MAX),
    source_info               NVARCHAR(MAX),
    structured_description    NVARCHAR(MAX),
    internal_agent_id         BIGINT,
    internal_group_id         BIGINT,
    sentiment_score           INT,
    initial_sentiment_score   INT,
    nr_due_by                 INT,
    nr_escalated              BIT,
    form_id                   BIGINT,
    snapshot_ts               DATETIME2 DEFAULT SYSUTCDATETIME()
);

-- Bulk import the json file
INSERT INTO Bronze.FreshdeskTickets (
    cc_emails,
    fwd_emails,
    reply_cc_emails,
    ticket_cc_emails,
    ticket_bcc_emails,
    fr_escalated,
    spam,
    email_config_id,
    group_id,
    priority,
    requester_id,
    responder_id,
    source,
    company_id,
    status,
    subject,
    association_type,
    support_email,
    to_emails,
    product_id,
    id,
    type,
    due_by,
    fr_due_by,
    is_escalated,
    custom_fields,
    created_at,
    updated_at,
    associated_tickets_count,
    tags,
    source_info,
    structured_description,
    internal_agent_id,
    internal_group_id,
    sentiment_score,
    initial_sentiment_score,
    nr_due_by,
    nr_escalated,
    form_id
)
SELECT
    JSON_VALUE(value, '$.cc_emails') AS cc_emails,
    JSON_VALUE(value, '$.fwd_emails') AS fwd_emails,
    JSON_VALUE(value, '$.reply_cc_emails') AS reply_cc_emails,
    JSON_VALUE(value, '$.ticket_cc_emails') AS ticket_cc_emails,
    JSON_VALUE(value, '$.ticket_bcc_emails') AS ticket_bcc_emails,
    JSON_VALUE(value, '$.fr_escalated') AS fr_escalated,
    JSON_VALUE(value, '$.spam') AS spam,
    JSON_VALUE(value, '$.email_config_id') AS email_config_id,
    JSON_VALUE(value, '$.group_id') AS group_id,
    JSON_VALUE(value, '$.priority') AS priority,
    JSON_VALUE(value, '$.requester_id') AS requester_id,
    JSON_VALUE(value, '$.responder_id') AS responder_id,
    JSON_VALUE(value, '$.source') AS source,
    JSON_VALUE(value, '$.company_id') AS company_id,
    JSON_VALUE(value, '$.status') AS status,
    JSON_VALUE(value, '$.subject') AS subject,
    JSON_VALUE(value, '$.association_type') AS association_type,
    JSON_VALUE(value, '$.support_email') AS support_email,
    JSON_QUERY(value, '$.to_emails') AS to_emails,
    JSON_VALUE(value, '$.product_id') AS product_id,
    JSON_VALUE(value, '$.id') AS id,
    JSON_VALUE(value, '$.type') AS type,
    JSON_VALUE(value, '$.due_by') AS due_by,
    JSON_VALUE(value, '$.fr_due_by') AS fr_due_by,
    JSON_VALUE(value, '$.is_escalated') AS is_escalated,
    JSON_QUERY(value, '$.custom_fields') AS custom_fields,
    JSON_VALUE(value, '$.created_at') AS created_at,
    JSON_VALUE(value, '$.updated_at') AS updated_at,
    JSON_VALUE(value, '$.associated_tickets_count') AS associated_tickets_count,
    JSON_QUERY(value, '$.tags') AS tags,
    JSON_VALUE(value, '$.source_info') AS source_info,
    JSON_VALUE(value, '$.structured_description') AS structured_description,
    JSON_VALUE(value, '$.internal_agent_id') AS internal_agent_id,
    JSON_VALUE(value, '$.internal_group_id') AS internal_group_id,
    JSON_VALUE(value, '$.sentiment_score') AS sentiment_score,
    JSON_VALUE(value, '$.initial_sentiment_score') AS initial_sentiment_score,
    JSON_VALUE(value, '$.nr_due_by') AS nr_due_by,
    JSON_VALUE(value, '$.nr_escalated') AS nr_escalated,
    JSON_VALUE(value, '$.form_id') AS form_id
FROM OPENROWSET(
    BULK 'C:\Users\michael.brostrom\Documents\GitHub\statistik-freshdesk-linear\raw\snapshot_30d\freshdesk_30d.json',
    SINGLE_CLOB
) AS raw
CROSS APPLY OPENJSON(raw.BulkColumn);
